### ISSUE TITLE
Mega Menu Tab Style hover Issue

### ISSUE THREAD

**Issue by arunsasi** [t3framework/t3#437] opened 2016-06-30 05:58 UTC
Mega menu tab style hover is not working perfectly on revisit
For example if we have 3 nav-child menu and sub child under the parent Menu.

**Products**

> **Child Product 1**
   > Sub Child 1
   > Sub Child 2
   > Sub Child 3

> **Child Product 2**
   > Sub Child 1
   > Sub Child 2
   > Sub Child 3

> **Child Product 3**
   > Sub Child 1
   > Sub Child 2
   > Sub Child 3

After page load, hover the menu **Product** the go to  **Child Product 3** then leave the sub menu drop down and hover any other main menu items. Then come back to menu **Product** now the **Child Product 3** 's sub child menus will load as default. If you hover  **Child Product 1** it will not show the sub child menus of **Child Product 1**. If you need to show the sub childs, you need to go and hover **Child Product 3**.

Any solution please....

**Comment by khanhlh** [comment] 2016-07-21 10:16
Can you give some screenshort of the issue?

**Comment by arunsasi** [comment] 2016-07-21 11:42
i will upload a video demo for the issue

**Comment by arunsasi** [comment] 2016-07-21 12:06
I have created a video. Please check it. Now Dropdown Trigger is Hover. If it is CLICK the issue is different

https://drive.google.com/file/d/0B1raGPNCJIxyY3dkRkFtR1NIMTQ/view?usp=drivesdk

If you need video for CLICK please tell me

**Comment by khanhlh** [comment] 2016-07-22 01:43
I still cannot reproduce the menu to find out a solution. Please provide step-by-step to create such menu.

**Comment by arunsasi** [comment] 2016-07-22 02:48
I have created a step by step video. Please check
https://drive.google.com/file/d/0B1raGPNCJIxyUnRnc0t4Ry10QjA/view

**Comment by khanhlh** [comment] 2016-07-22 03:53
I got it. The issue will be fixed in coming release.

**Closed** 2016-07-22 04:25 UTC
